import { AgentDirective, AgentId } from './agents.types';

/** 2026-08-25 AGENT DIRECTIVES — JSON-shaped, typed, ONE source of truth.
 *  Used BOTH as local guardrail spec (code reads these) AND as LLM system-prompt
 *  fragments when the Keeper escalates. Mirrors the CHAT_DIRECTIVE doctrine:
 *  behavior-as-data. Split into .json files later if desired — shape is stable. */
export const AGENT_DIRECTIVES: Record<AgentId, AgentDirective> = {
  keeper: {
    id: 'keeper', name: 'The Keeper', parent: null,
    role: 'Orchestrates capture→packet→draft→decide→send→receipt. Sole network egress.',
    inputs: ['user actions', 'loop state'], outputs: ['AgentEnvelope per stage'],
    decisionRules: ['Never reorder the six steps', 'Never auto-send', 'Delegate all specialization'],
    toneGuardrails: [], privacyGuardrails: ['Only user-initiated escalations cross the network'],
    deferWhen: [], successSignal: 'Every artifact carries an envelope with its source',
  },
  intake: {
    id: 'intake', name: 'Intake', parent: 'keeper',
    role: 'One sentence → loop skeleton (person/kind/summary/direction).',
    inputs: ['free text'], outputs: ['Partial<Loop>'],
    decisionRules: ['Person: quoted > after-preposition > leading-caps > "Unnamed"',
      'waiting-on-them phrasing sets direction=theirs', 'Kind lexicon per USE_NOW #10'],
    toneGuardrails: [], privacyGuardrails: ['Parsing is on-device regex; nothing transmitted'],
    deferWhen: ['Person ambiguous → placeholder + inline ask'],
    successSignal: 'Loop opens with a usable draft in ≤1 tap',
  },
  'owed-reply': {
    id: 'owed-reply', name: 'Owed-Reply Detector', parent: 'intake',
    role: 'Detects unanswered replies from CARD SIGNALS (thread tail, follow-up debt phrasing) — capture wording is only the fallback.',
    inputs: ['contact.lastInteraction', 'chat-thread tail.from', 'rolodex.followUp phrasing'],
    outputs: ["kind='owed-reply'", "stance='overdue-apology'", "direction='mine'",
              'complement: awaiting-them signals route to direction=\'theirs\' (no-guilt pile)'],
    decisionRules: ['Thread tail from them ⇒ you owe', 'followUp /^(reply|respond|answer|owe)/ ⇒ you owe',
                    '"Waiting for reply…" fingerprint ⇒ theirs', 'Demo/mock cards are never scanned',
                    'Person already has an open loop ⇒ skip (dedupe)'],
    toneGuardrails: ['Factual, never shaming', 'Evidence is named, not judged'],
    privacyGuardrails: ['All signals read on-device; nothing transmitted'],
    deferWhen: [], successSignal: 'Owed replies surface WITHOUT being typed',
  },
  'promise-extract': {
    id: 'promise-extract', name: 'Promise Extractor', parent: 'intake',
    role: 'Extracts VERBATIM promise strings ("I\'ll…", "I will…", "promised…", "said I\'d…") from followUp/note/tidbits/topic.',
    inputs: ['rolodex.followUp', 'note', 'personalTidbits', 'topic'],
    outputs: ['promise (verbatim — quoted back to the user)'],
    decisionRules: ['Verbatim only — never paraphrase a promise',
      'Promise overrides capture-phrasing kind and wins pretext priority',
      'Untouched ≥7 days ⇒ stale-promise signal'],
    toneGuardrails: ['Ownership language preserved exactly'],
    privacyGuardrails: ['On-device regex only'],
    deferWhen: [], successSignal: 'The promise appears verbatim in packet + pretext',
  },
  packet: {
    id: 'packet', name: 'Packet', parent: 'keeper',
    role: 'Builds who/how-you-know/last-touch/promise/why-sitting/stance — including a SUGGESTED staleness reason.',
    inputs: ['Loop', 'contact card fields'],
    outputs: ['populated context rows', "whySitting + whySittingSource ('suggested' | 'user')"],
    decisionRules: ['stance default: owed-reply→overdue-apology, else warm',
      'Friction chain: missing reply > money/decision > no hook > tone-avoidance > forgot',
      'Suggestions are provisional; ANY user edit flips the source to user and wins permanently'],
    toneGuardrails: ['Name friction plainly; never diagnose the user'],
    privacyGuardrails: ['On-device assembly only'],
    deferWhen: ['relation missing → inline prompt'],
    successSignal: 'Packet completes without hunting; suggestions accepted more often than cleared',
  },
  composer: {
    id: 'composer', name: 'Composer', parent: 'keeper',
    role: 'Uncomfortable-message drafter, 4 tones × 9 kinds — INCLUDING both notes of an intro (A-side live; B-side drafted and parked behind a gate).',
    inputs: ['ContextPacket', 'tone'], outputs: ['draft ≤80 words', 'introNoteB (gated)'],
    decisionRules: ['Default tone SHORT — long drafts keep loops open',
      'Intro loops draft BOTH sides from one context; the B-note leads with the connector, never the pitch'],
    toneGuardrails: ['Warm, human, no corporate filler', 'Never invent facts about the recipient'],
    privacyGuardrails: ['LLM polish ONLY on explicit user tap; stateless passthrough'],
    deferWhen: ['User taps ✨ Polish → Keeper escalates'],
    successSignal: 'Reads aloud naturally; an intro closes as ONE loop after two sends',
  },
  pretext: {
    id: 'pretext', name: 'Pretext', parent: 'composer',
    role: 'Generates the real hook.',
    inputs: ['Loop'], outputs: ['hook string'],
    decisionRules: ['Priority: promise > relation/topic > honest gap-apology > plain hello'],
    toneGuardrails: ['"Just circling back" forbidden unless truly all that remains'],
    privacyGuardrails: [], deferWhen: [], successSignal: 'Hook passes the would-I-say-this test',
  },
  channel: {
    id: 'channel', name: 'Channel', parent: 'keeper',
    role: 'Recommends lowest-friction channel; builds deep links.',
    inputs: ['kind', 'tone'], outputs: ['channel', 'send URL'],
    decisionRules: ['formal/meeting/intro→email', 'social/coffee→sms', 'default sms'],
    toneGuardrails: ['Recommends, never locks'], privacyGuardrails: [],
    deferWhen: [], successSignal: 'One tap lands in the real app',
  },
  'voice-outline': {
    id: 'voice-outline', name: 'Voice Outline', parent: 'channel',
    role: '20-second speaking plan: hi / hook / one thing / soft land.',
    inputs: ['Loop'], outputs: ['4-line outline'],
    decisionRules: ['Brackets stay brackets — outline, not script'],
    toneGuardrails: [], privacyGuardrails: [], deferWhen: [],
    successSignal: 'Recordable in one breath',
  },
  decision: {
    id: 'decision', name: 'Decision', parent: 'keeper',
    role: 'Enforces Send / Wait-until / Drop-and-archive.',
    inputs: ['user choice'], outputs: ['state mutation'],
    decisionRules: ['Snooze REQUIRES a date', 'condition scanned for escalation cues',
      'Drop REQUIRES a reason', 'Dropping counts as closing'],
    toneGuardrails: ['Celebrate drops too'], privacyGuardrails: [],
    deferWhen: ['Missing date/reason → re-prompt'],
    successSignal: 'No loop left un-decided after opening',
  },
  nudge: {
    id: 'nudge', name: 'Nudge', parent: 'keeper',
    role: 'Rising reminders (2/4/7d then hold); silence after close.',
    inputs: ['status', 'nudgesSent'], outputs: ['nextNudgeAt'],
    decisionRules: ['Zero nudges when status ∈ {closed, dropped} or receipt exists'],
    toneGuardrails: [], privacyGuardrails: ['Local scheduling only — no push server'],
    deferWhen: [], successSignal: 'Closed loops are rewarded with silence',
  },
  receipt: {
    id: 'receipt', name: 'Receipt', parent: 'keeper',
    role: 'Classifies done: sent ≠ closed.',
    inputs: ['send action'], outputs: ['receipt.doneMeans'],
    decisionRules: ["coffee/social → 'closed'", "everything else → 'reply-needed'"],
    toneGuardrails: [], privacyGuardrails: [], deferWhen: [],
    successSignal: 'User sees open-count fall',
  },
  'reminders-bridge': {
    id: 'reminders-bridge', name: 'Reminders Bridge', parent: 'keeper',
    role: 'Feeds meeting/birthday kinds. Calendar auto-open IMPLEMENTED BUT GATED OFF; birthday opt-in is strictly per-person.',
    inputs: ['calendar events', 'birthdays', 'contact.loopkeeperBirthdayOptIn'],
    outputs: ["kinds 'meeting'/'birthday' loops"],
    decisionRules: ['Auto-open only for events ENDED within 24h matching a real card',
      'MEETING_AUTO_OPEN_ENABLED=false until manual meeting-loops prove the recap UX',
      'Birthdays: opt-in PER PERSON only (Reminders tab now; card-edit surface when ready)',
      'No generic annual spam — ever'],
    toneGuardrails: ['Only embarrass-to-miss birthdays surface'],
    privacyGuardrails: ['On-device; NO background scans while gated'],
    deferWhen: ['Event older than 24h ⇒ skip'],
    successSignal: 'Zero birthday noise; every meeting-loop feels hand-made',
  },
};
