import { AgentDirective, AgentId } from './agents.types';

/** 2026-08-25 AGENT DIRECTIVES — JSON-shaped, typed, ONE source of truth.
 *  Used BOTH as local guardrail spec (code reads these) AND as LLM system-prompt
 *  fragments when the Keeper escalates. Mirrors the CHAT_DIRECTIVE doctrine:
 *  behavior-as-data. Split into .json files later if desired — shape is stable. */
export const AGENT_DIRECTIVES: Record<AgentId, AgentDirective> = {
  keeper: {
    id: 'keeper', name: 'The Keeper', parent: null,
    role: 'Orchestrates capture→packet→draft→decide→send→receipt. Sole network egress.',
    inputs: ['user actions', 'loop state'], outputs: ['AgentEnvelope per stage'],
    decisionRules: ['Never reorder the six steps', 'Never auto-send', 'Delegate all specialization'],
    toneGuardrails: [], privacyGuardrails: ['Only user-initiated escalations cross the network'],
    deferWhen: [], successSignal: 'Every artifact carries an envelope with its source',
  },
  intake: {
    id: 'intake', name: 'Intake', parent: 'keeper',
    role: 'One sentence → loop skeleton (person/kind/summary/direction).',
    inputs: ['free text'], outputs: ['Partial<Loop>'],
    decisionRules: ['Person: quoted > after-preposition > leading-caps > "Unnamed"',
      'waiting-on-them phrasing sets direction=theirs', 'Kind lexicon per USE_NOW #10'],
    toneGuardrails: [], privacyGuardrails: ['Parsing is on-device regex; nothing transmitted'],
    deferWhen: ['Person ambiguous → placeholder + inline ask'],
    successSignal: 'Loop opens with a usable draft in ≤1 tap',
  },
  'owed-reply': {
    id: 'owed-reply', name: 'Owed-Reply Detector', parent: 'intake',
    role: 'Flags unanswered threads as the highest-guilt class.',
    inputs: ['inbound/outbound signals'], outputs: ["kind='owed-reply'", "stance='overdue-apology'"],
    decisionRules: ['Boost Today\'s 3 score above check-ins'],
    toneGuardrails: ['Factual, never shaming'], privacyGuardrails: [],
    deferWhen: [], successSignal: 'Owed replies surface first',
  },
  'promise-extract': {
    id: 'promise-extract', name: 'Promise Extractor', parent: 'intake',
    role: 'Finds "I\'ll…" commitments in notes/follow-ups.',
    inputs: ['note/followUp text'], outputs: ['promise string'],
    decisionRules: ['Promise text wins pretext priority over generic hooks'],
    toneGuardrails: ['Quote verbatim, never paraphrase'], privacyGuardrails: [],
    deferWhen: [], successSignal: 'Promise appears in the packet',
  },
  packet: {
    id: 'packet', name: 'Packet', parent: 'keeper',
    role: 'Builds who/how-you-know/last-touch/promise/why-sitting/stance.',
    inputs: ['Loop', 'contact card fields'], outputs: ['populated context rows'],
    decisionRules: ['stance default: owed-reply→overdue-apology, else warm'],
    toneGuardrails: ['whySitting is user-editable truth — never fabricated'],
    privacyGuardrails: ['On-device assembly only'],
    deferWhen: ['relation missing → inline prompt'],
    successSignal: 'Packet complete without user hunting through notes',
  },
  composer: {
    id: 'composer', name: 'Composer', parent: 'keeper',
    role: 'Uncomfortable-message drafter across 4 tones × 9 kinds.',
    inputs: ['ContextPacket', 'tone'], outputs: ['draft ≤80 words'],
    decisionRules: ['Default tone SHORT — long drafts keep loops open'],
    toneGuardrails: ['Warm, human, no corporate filler', 'Never invent facts about the recipient'],
    privacyGuardrails: ['LLM polish ONLY on explicit user tap; stateless passthrough'],
    deferWhen: ['User taps ✨ Polish → Keeper escalates'],
    successSignal: 'Draft reads aloud naturally',
  },
  pretext: {
    id: 'pretext', name: 'Pretext', parent: 'composer',
    role: 'Generates the real hook.',
    inputs: ['Loop'], outputs: ['hook string'],
    decisionRules: ['Priority: promise > relation/topic > honest gap-apology > plain hello'],
    toneGuardrails: ['"Just circling back" forbidden unless truly all that remains'],
    privacyGuardrails: [], deferWhen: [], successSignal: 'Hook passes the would-I-say-this test',
  },
  channel: {
    id: 'channel', name: 'Channel', parent: 'keeper',
    role: 'Recommends lowest-friction channel; builds deep links.',
    inputs: ['kind', 'tone'], outputs: ['channel', 'send URL'],
    decisionRules: ['formal/meeting/intro→email', 'social/coffee→sms', 'default sms'],
    toneGuardrails: ['Recommends, never locks'], privacyGuardrails: [],
    deferWhen: [], successSignal: 'One tap lands in the real app',
  },
  'voice-outline': {
    id: 'voice-outline', name: 'Voice Outline', parent: 'channel',
    role: '20-second speaking plan: hi / hook / one thing / soft land.',
    inputs: ['Loop'], outputs: ['4-line outline'],
    decisionRules: ['Brackets stay brackets — outline, not script'],
    toneGuardrails: [], privacyGuardrails: [], deferWhen: [],
    successSignal: 'Recordable in one breath',
  },
  decision: {
    id: 'decision', name: 'Decision', parent: 'keeper',
    role: 'Enforces Send / Wait-until / Drop-and-archive.',
    inputs: ['user choice'], outputs: ['state mutation'],
    decisionRules: ['Snooze REQUIRES a date', 'condition scanned for escalation cues',
      'Drop REQUIRES a reason', 'Dropping counts as closing'],
    toneGuardrails: ['Celebrate drops too'], privacyGuardrails: [],
    deferWhen: ['Missing date/reason → re-prompt'],
    successSignal: 'No loop left un-decided after opening',
  },
  nudge: {
    id: 'nudge', name: 'Nudge', parent: 'keeper',
    role: 'Rising reminders (2/4/7d then hold); silence after close.',
    inputs: ['status', 'nudgesSent'], outputs: ['nextNudgeAt'],
    decisionRules: ['Zero nudges when status ∈ {closed, dropped} or receipt exists'],
    toneGuardrails: [], privacyGuardrails: ['Local scheduling only — no push server'],
    deferWhen: [], successSignal: 'Closed loops are rewarded with silence',
  },
  receipt: {
    id: 'receipt', name: 'Receipt', parent: 'keeper',
    role: 'Classifies done: sent ≠ closed.',
    inputs: ['send action'], outputs: ['receipt.doneMeans'],
    decisionRules: ["coffee/social → 'closed'", "everything else → 'reply-needed'"],
    toneGuardrails: [], privacyGuardrails: [], deferWhen: [],
    successSignal: 'User sees open-count fall',
  },
  'reminders-bridge': {
    id: 'reminders-bridge', name: 'Reminders Bridge', parent: 'keeper',
    role: 'Feeds meeting/birthday kinds from FollowUpEngine + BirthdayReminderService.',
    inputs: ['calendar events', 'birthdays'], outputs: ["kinds 'meeting'/'birthday' loops"],
    decisionRules: ['Birthdays opt-in per person only'],
    toneGuardrails: ['No generic annual spam'], privacyGuardrails: ['On-device'],
    deferWhen: [], successSignal: 'Only embarrass-to-miss birthdays surface',
  },
};
